name: MinecraftManhunt
version: 1.3.3.9
main: com.yoonicode.minecraftmanhuntplus.PluginMain
api-version: 1.18
description: Manhunt plugin
commands:
  hunter:
    description: Register a player as a manhunt Hunter.
    usage: /hunter <target>
    permission: minecraftmanhuntplus.hunter
  runner:
    description: Register a player as a manhunt runner.
    usage: /runner <target>
    permission: minecraftmanhuntplus.speedrunner
  spectator:
    description: Register a player as a manhunt Spectator.
    usage: /spectator <target>
    permission: minecraftmanhuntplus.spectator
  clearteams:
    description: Clears teams and removes Discord roles.
    usage: /clearteams
    permission: minecraftmanhuntplus.clearteams
  start:
    description: Start the Manhunt game.
    usage: /start
    permission: minecraftmanhuntplus.start
  end:
    description: Stops the Manhunt game.
    usage: /end
    permission: minecraftmanhuntplus.end
  setheadstart:
    description: Sets the headStartDuration field in plugin config, in seconds.
    usage: /setheadstart <seconds>
    permission: minecraftmanhuntplus.config
  compass:
    description: Use to obtain a compass.
    usage: /compass
    permission: minecraftmanhuntplus.compass
  hunterhelp:
    description: Hunter gets extra advantage when killed by runner.
    usage: /hunterhelp
    permission: minecraftmanhuntplus.hunterhelp
  runnerhelp:
    description: Runner gets extra advantage after killing a hunter.
    usage: /runnerhelp
    permission: minecraftmanhuntplus.runnerhelp
  extradrops:
    description: Drops extra items on hunter deaths.
    usage: /extradrops
    permission: minecraftmanhuntplus.extradrops
  chestgenerate:
    description: Small chance that when a player breaks a block, it turns into a chest with random items.
    usage: /chestgenerate
    permission: minecraftmanhuntplus.chestgenerate
  hasteboost:
    description: Every player has unlimited haste
    usage: /hasteboost
    permission: minecraftmanhuntplus.hasteboost
  allhelp:
    description: Enable all help hunterhelp, runnerhelp, etc.
    usage: /allhelp
    permission: minecraftmanhuntplus.allhelp
  cutclean:
    description: Enables cutclean
    usage: /cutclean
    permission: minecraftmanhuntplus.cutclean
  pause:
    description: Pauses the game
    usage: /pause
    permission: minecraftmanhuntplus.pause
  unpause:
    description: Unpauses the game
    usage: /unpause
    permission: minecraftmanhuntplus.unpause
