name: MinecraftManhunt
version: 1.3.3.9
main: manhunt_plus.PluginMain
api-version: 1.18
description: Manhunt plugin
depend: [ProtocolLib]
commands:
  hunter:
    description: Register a player as a manhunt Hunter.
    usage: /hunter <target>
    permission: manhunt_plus.hunter
  runner:
    description: Register a player as a manhunt runner.
    usage: /runner <target>
    permission: manhunt_plus.speedrunner
  spectator:
    description: Register a player as a manhunt Spectator.
    usage: /spectator <target>
    permission: manhunt_plus.spectator
  clearteams:
    description: Clears teams and removes Discord roles.
    usage: /clearteams
    permission: manhunt_plus.clearteams
  start:
    description: Start the Manhunt game.
    usage: /start
    permission: manhunt_plus.start
  end:
    description: Stops the Manhunt game.
    usage: /end
    permission: manhunt_plus.end
  setheadstart:
    description: Sets the headStartDuration field in plugin config, in seconds.
    usage: /setheadstart <seconds>
    permission: manhunt_plus.config
  compass:
    description: Use to obtain a compass.
    usage: /compass
    permission: manhunt_plus.compass
  hunterhelp:
    description: Hunter gets extra advantage when killed by runner.
    usage: /hunterhelp
    permission: manhunt_plus.hunterhelp
  runnerhelp:
    description: Runner gets extra advantage after killing a hunter.
    usage: /runnerhelp
    permission: manhunt_plus.runnerhelp
  extradrops:
    description: Drops extra items on hunter deaths.
    usage: /extradrops
    permission: manhunt_plus.extradrops
  chestgenerate:
    description: Small chance that when a player breaks a block, it turns into a chest with random items.
    usage: /chestgenerate
    permission: manhunt_plus.chestgenerate
  hasteboost:
    description: Every player has unlimited haste
    usage: /hasteboost
    permission: manhunt_plus.hasteboost
  allhelp:
    description: Enable all help hunterhelp, runnerhelp, etc.
    usage: /allhelp
    permission: manhunt_plus.allhelp
  cutclean:
    description: Enables cutclean
    usage: /cutclean
    permission: manhunt_plus.cutclean
  pause:
    description: Pauses the game
    usage: /pause
    permission: manhunt_plus.pause
  unpause:
    description: Unpauses the game
    usage: /unpause
    permission: manhunt_plus.unpause
  health:
    description: Sets the health of the player
    usage: /health <value>
    permission: manhunt_plus.health
  supplyDrops:
    description: Enables supply drops
    usage: /supplydrops
    permission: manhunt_plus.supplydrops